# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
# template for the changelog header
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""
# template for the changelog body
# https://keats.github.io/tera/docs/#introduction
body = """
{%- macro remote_url() -%}
  https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}
{%- endmacro -%}

{% if version %}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}

{% if commits | filter(attribute="breaking", value=true) | length != 0 %}
    ### Breaking Changes
    {% for commit in commits | filter(attribute="breaking", value=true) %}
        {{ " " }}- {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.pr_number %} in \
            [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endif -%}

{% for group, commits in commits | filter(attribute="breaking", value=false) | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        {{ " " }}- {{ commit.message | split(pat="\n") | first | upper_first | trim }}\
            {% if commit.remote.pr_number %} in \
            [#{{ commit.remote.pr_number }}]({{ self::remote_url() }}/pull/{{ commit.remote.pr_number }}) \
            {%- endif -%}
    {% endfor %}
{% endfor %}
### Commit Details

<details><summary>view details</summary>

{% for commit in commits -%}
    {{ " " }}* {{ commit.raw_message | split(pat="\n") | first | trim }} ([`{{ commit.id |  truncate(length=7, end="") }}`]({{ self::remote_url() }}/commit/{{ commit.id}}))
{% endfor -%}
</details>

"""
# template for the changelog footer
footer = """
<!-- generated by git-cliff -->
"""
# remove the leading and trailing whitespace from the templates
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_preprocessors = [
    # replace issues with issue links
    { pattern = '\((\w+\s)?#([0-9]+)\)', replace = "([#${2}](https://github.com/z0w13/tulpje/issues/${2}))" },
]
# regex for parsing and grouping commits
commit_parsers = [
    { message = "^release", skip = true },
    { message = "^.*: release", skip = true },
    { message = "^[a|A]dd", group = "Added" },
    { message = "^[s|S]upport", group = "Added" },
    { message = "^[r|R]emove", group = "Removed" },
    { message = "^.*: add", group = "Added" },
    { message = "^.*: support", group = "Added" },
    { message = "^.*: remove", group = "Removed" },
    { message = "^.*: delete", group = "Removed" },
    { message = "^test", group = "Fixed" },
    { message = "^fix", group = "Fixed" },
    { message = "^.*: fix", group = "Fixed" },
    { message = "^.*", group = "Changed" },
]
# filter out the commits that are not matched by commit parsers
filter_commits = true
topo_order = false
sort_commits = "newest"
