name: "Continuous Integration"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: nixbuild/nix-quick-install-action@2c9db80fb984ceb1bcaa77cdda3fdf8cfba92035 # v34
      - uses: cachix/cachix-action@1eb2ef646ac0255473d23a5907ad7b04ce94065c # v17
        with:
          name: tulpje
          authToken: "${{ secrets.CACHIX_TOKEN }}"
      - name: Build binaries
        run: nix build .
      - name: Build docker images
        run: nix build .#docker-gateway .#docker-handler .#docker-gateway-queue .#docker-nirn-proxy
