name: "Build Docker Images"
on:
  push:
    tags: [ "v*" ]
jobs:
  build:
    strategy:
      matrix:
        image:
          - { output: "docker-gateway", name: "tulpje-gateway" }
          - { output: "docker-handler", name: "tulpje-handler" }
          - { output: "docker-http-proxy", name: "twilight-http-proxy"}
          - { output: "docker-gateway-queue", name: "twilight-gateway-queue" }
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Install Nix"
        uses: nixbuild/nix-quick-install-action@v30
      - name: "Login to registry"
        run: echo "${{ secrets.GITHUB_TOKEN}}" | skopeo login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: "Generate image tag"
        id: image-tag
        run: |
          REF_NAME=${{ github.ref_name }}
          DOCKER_TAG=${REF_NAME#v}
          echo "name=$DOCKER_TAG" >> "$GITHUB_OUTPUT"
      - name: Build ${{ matrix.image.name }} image
        run: nix build -o ${{ matrix.image.output }}.tar.gz .#${{ matrix.image.output }}
      - name: Push ${{ matrix.image.name }} image
        run: >
          skopeo --insecure-policy copy
          "docker-archive:${{ matrix.image.output }}.tar.gz"
          "docker://ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/${{ matrix.image.name }}:${{ steps.image-tag.outputs.name }}"
